# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:             Musings
description:      ''

author:
  name:           '@kvsrh'
  url:            https://github.com/kvsrh

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/kvsrh
